Turn off env chaining in .github/workflows/ubuntu-ci-x86_64-oneapi.yaml

diff --git a/.github/workflows/ubuntu-ci-x86_64-oneapi.yaml b/.github/workflows/ubuntu-ci-x86_64-oneapi.yaml
--- a/.github/workflows/ubuntu-ci-x86_64-oneapi.yaml
+++ b/.github/workflows/ubuntu-ci-x86_64-oneapi.yaml
@@ -224,19 +224,19 @@ jobs:
           spack stack setup-meta-modules
           spack env deactivate
 
-          # Test environment chaining
-          echo "Test environment chaining"
-          spack stack create env --name chaintest --template empty --site linux.default --upstream ${ENVDIR}/install --compiler intel
-          # Retain config from upstream so we don't have to rebuild:
-          cp -r ${ENVDIR}/{site,common} $PWD/envs/chaintest/.
-          spack env activate ${PWD}/envs/chaintest
-          # Pin gmake to avoid duplicate packages (excluded gmake from spack external find above)
-          spack config add "packages:gmake:require:'@:4.2'"
-          spack add nccmp@1.9.0.1%oneapi
-          spack concretize | tee envs/chaintest/log.concretize
-          unwanted_duplicates=$(( cat envs/chaintest/log.concretize | grep -E '^ - ' | grep -Fv 'nccmp@1.9.0.1' || true ) | wc -l)
-          if [ ${unwanted_duplicates} -gt 0 ]; then echo "Environment chaining test failed"; exit 1; fi
-          spack env deactivate
+          ### # Test environment chaining
+          ### echo "Test environment chaining"
+          ### spack stack create env --name chaintest --template empty --site linux.default --upstream ${ENVDIR}/install --compiler intel
+          ### # Retain config from upstream so we don't have to rebuild:
+          ### cp -r ${ENVDIR}/{site,common} $PWD/envs/chaintest/.
+          ### spack env activate ${PWD}/envs/chaintest
+          ### # Pin gmake to avoid duplicate packages (excluded gmake from spack external find above)
+          ### spack config add "packages:gmake:require:'@:4.2'"
+          ### spack add nccmp@1.9.0.1%oneapi
+          ### spack concretize | tee envs/chaintest/log.concretize
+          ### unwanted_duplicates=$(( cat envs/chaintest/log.concretize | grep -E '^ - ' | grep -Fv 'nccmp@1.9.0.1' || true ) | wc -l)
+          ### if [ ${unwanted_duplicates} -gt 0 ]; then echo "Environment chaining test failed"; exit 1; fi
+          ### spack env deactivate
 
       - name: test-env
         run: |
