ubuntu-ci-x86_64.yaml

diff --git a/.github/workflows/ubuntu-ci-x86_64.yaml b/.github/workflows/ubuntu-ci-x86_64.yaml
--- a/.github/workflows/ubuntu-ci-x86_64.yaml
+++ b/.github/workflows/ubuntu-ci-x86_64.yaml
@@ -156,9 +156,8 @@ jobs:
           spack env activate ${PWD}/envs/chaintest
           spack add nccmp@1.8.9.0%intel
           cat envs/chaintest/spack.yaml
-          spack concretize -f | grep -E '^ - ' # | grep -Fv 'nccmp@1.8.9.0' | wc -l)
-          exit 1
-          if [ ${unwanted_duplicates} -gt 0 ]; then echo hello; exit 1; fi
+          unwanted_duplicates=$(spack concretize -f | grep -E '^ - ' | grep -Fv 'nccmp@1.8.9.0' | wc -l)
+          if [ ${unwanted_duplicates} -gt 0 ]; then echo "Env chaining test failed"; exit 1; fi
           spack env deactivate
           spack env activate envs/ci-env.ubuntu-ci-x86_64
           # DH* 20230721 - todo remove || true (this was here all the time, but should not be needed if spack creates buildcaches correctly)
